name: ui-fetcher CI
on:
  push:
    branches: ['main', 'develop', 'release']
  pull_request:
    branches: ['main', 'develop', 'release']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and PNPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Cache PNPM packages
          registry-url: 'https://registry.npmjs.org'
          scope: '@global'

      - run: npm install -g pnpm # Install PNPM globally

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - run: pnpm test
